spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/batch_test
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always